# -*- coding: utf-8 -*-
"""Project_Lead.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pmgryxbtKJkYfyDXATbi4PKxXHfCe5cS

# **Library**
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Data Base**"""

# Data base

DB = "Leads.csv"

# Creating DF

df = pd.read_csv(DB)

df_interaction = df[['Total Time Spent on Website', 'Converted','Page Views Per Visit']]

# Structure verification

df.head()

# Separation of columns of interest

df_filter = df[['Lead Number', 'Lead Origin', 'Lead Source', 'Converted', 'Total Time Spent on Website', 'Lead Profile', 'Lead Quality', 'Country', 'City', 'Page Views Per Visit', 'How did you hear about X Education']]

df_filter.head()

"""# **Data Modeling**

## **Convertion per Lead Source**
"""

# Selecting Columns

df_source_converted = df_filter.groupby('Lead Source')['Converted'].sum().reset_index()

df_source_converted

df_source_converted = df_source_converted.loc[df_source_converted['Converted'] > 0]

df_source_converted

plt.figure(figsize = (10, 6))
sns.barplot(x= 'Converted', y='Lead Source', data=df_source_converted)
plt.xlabel('Lead Source')
plt.ylabel('Converted')
plt.title('Convertion per Lead Source')
plt.show()

"""## **Region with more converting**"""

# Selecting Columns

df_region_converted = df_filter.groupby(['Country', 'City'])['Converted'].sum().reset_index()

df_region_converted = df_region_converted[df_region_converted['Converted'] > 0]

# Filtering only per Country
df_region_converted = df_region_converted.groupby('Country')['Converted'].sum()

df_region_converted

"""## **Interaction**"""

df_interaction = df[['Total Time Spent on Website', 'Converted','Page Views Per Visit']]

df_interaction

df_interaction['Total Time Spent on Website'].mean()